config/routes.rb
Rails.application.routes.draw do
    root to: 'pages#home'
    get 'about', to: 'pages#about'
    get 'contact_us', to: 'pages#contact_us'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    
    def about
    end

    def contact_us
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Saasapp</title>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <%= link_to root_path, class: "navbar-brand" do %>
              <i class ="fa fa-group"></i>
              DevMatch
            <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact us", contact_us_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    
      <%= yield %>

  </body>
</html>

app/views/pages/about.html.erb
<div class="container text-center">
    <h1>About Page</h1>
    <p>We are DevMatch. Our company focuses on creating an exclusive community 
    for developers and entrepreneurs to meet.</p>
</div>

app/views/pages/contact_us.html.erb
<h1>hi</h1>
<div id="map" style="width:400px;height:400px;"</div>

<script>
   function myMap() {
    var mapOptions = {
        center: new google.maps.LatLng(43.583521, -79.654510),
        zoom: 12,
        mapTypeId: google.maps.MapTypeId.ROADMAP
    }
var map = new google.maps.Map(document.getElementById("map"), mapOptions);
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?callback=myMap"></script>

app/views/pages/home.html.erb
<div class="home-callout text-center container-fluid">
    <h1>Welcome to DevMatch</h1>
    <h3>A membership site where entrepeneurs can meet developers.</h3>
</div>